

spring:
  application:
    name: AlumniManagement

  datasource:
    password: O1933419@postgres
    url: jdbc:postgresql://localhost:5432/AlumniManagement
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:8180
  realm: CS545WAA-FinalProject
  resource: waa-june-2022-final-project
  public-client: true

#keycloak.security-constraints[0].authRoles[0]=USER
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/customers/*
#keycloak.security-constraints[0].authRoles[1]=ADMIN
#keycloak.security-constraints[0].securityCollections[0].patterns[1]=/customers/*
#keycloak.principal-attribute=preferred_username

